[package]
name = "hone"
version = "0.5.0"
edition = "2021"
description = "Hone - 轻量级、跨平台、可嵌入的脚本语言（单文件解释器）"
license = "MIT"

[[bin]]
name = "hone"
path = "src/main.rs"

[profile.release]
lto = true
opt-level = "z"
strip = true
debug = false
panic = "abort"
codegen-units = 1

[dependencies]
serde_json = "1"
libloading = "0.7"
regex = "1"
md-5 = "0.10"
sha2 = "0.10"
sha1 = "0.10"
hmac = "0.12"
base64 = "0.22"
zip = { version = "2", default-features = false, features = ["deflate"] }
tar = "0.4"
flate2 = "1"
once_cell = "1"
# TLS：rustls + rustls-rustcrypto（纯 Rust，无 C 依赖），Windows/Linux/Termux 跨平台一致
rustls = { version = "0.23", default-features = false, features = ["std", "tls12"] }
rustls-rustcrypto = "0.0.2-alpha"
webpki-roots = "0.26"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "winbase", "winreg", "synchapi", "errhandlingapi", "winnt"] }
